### ISSUE TITLE
Cygwin: "make -s console" fails with ImportError: No module named msvcrt

### ISSUE THREAD

**Issue by wingstar74** [eerimoq/simba#14] opened 2016-05-30 20:19 UTC
$ make -s console
Traceback (most recent call last):
  File "../../simba/simba/make/console.py", line 6, in <module>
    import readchar
  File "/usr/lib/python2.7/site-packages/readchar/__init__.py", line 3, in <module>
    from .readchar import readchar, readkey
  File "/usr/lib/python2.7/site-packages/readchar/readchar.py", line 13, in <module>
    from .readchar_windows import readchar
  File "/usr/lib/python2.7/site-packages/readchar/readchar_windows.py", line 5, in <module>
    import msvcrt
ImportError: No module named msvcrt
../../simba/simba/make/app.mk:137: receptet för målet ”console” misslyckades
make: *** [console] Fel 1

Note that readchar is installed

**Comment by eerimoq** [comment] 2016-05-30 20:27
What about "ImportError: No module named msvcrt"? Maybe pip did not install that dependency?

**Comment by eerimoq** [comment] 2016-05-30 20:31
Meh, looks like readchar does not work in Cygwin. msvcrt is only available in Python for Windows.

**Comment by eerimoq** [comment] 2016-05-30 20:53
The problem is that readchar imports the windows version in Cygwin, when it should incluse the linux version instead. I manually modified /lib/python2.7/site-packages/readchar/readchar.py to import the linux version and then the console works.

**Comment by eerimoq** [comment] 2016-05-30 21:33
Copied readchar release 1.1.0 to the 3pp folder and made required changes. Committed in 2bf89cbfd1340f9c81a15fe7597c55a942f84680.

**Closed by eerimoq** 2016-05-30 21:33 UTC
Labels: bug
